# Pandas

# #Pandas is an open‑source Python library that provides fast, flexible data structures—mainly Series and DataFrame—for data manipulation and analysis, built on top of NumPy.

In [1]:
# developed by mckinney in 20098

In [2]:
import random

In [3]:
import pandas as pd

In [4]:
pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv")

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,NaN,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,NaN,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,979-833159409-1,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,Andrew K.; Zia A.; Rizzo D.,"Andrew, Kevin (59264606600); Zia, Asim (572234...",59264606600; 57223446194; 7005922424,Integrating Deep Reinforcement Learning into A...,2024,Lecture Notes in Networks and Systems,1066 LNNS,NaN,NaN,221,...,978-303166427-4,NaN,NaN,English,Lect. Notes Networks Syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85201106911
871,Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.,"Tew, Yishen (58700122400); Fu, Ling (577214082...",58700122400; 57721408200; 59081900100; 5772168...,Construction of Knowledge Graph for Material a...,2024,Energy Proceedings,44,NaN,NaN,NaN,...,NaN,NaN,NaN,English,Energy. Proc.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85190366728
872,Ullah K.M.; Oladosu G.A.; Crooks A.,"Ullah, Kazi Masel (56239217200); Oladosu, Gbad...",56239217200; 6602587328; 25521036800,Evaluating the incentive for soil organic carb...,2023,Journal of Environmental Management,348,NaN,119418,NaN,...,NaN,JEVMA,37871549.0,English,J. Environ. Manage.,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-85174450993
873,Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...,"Shen, Weiwei (57346991900); Marín Del Valle, T...",57346991900; 57226063061; 57196091876; 5719626...,Scenario analyses of mariculture expansion in ...,2024,"Resources, Conservation and Recycling",204,NaN,107508,NaN,...,NaN,RCREE,NaN,English,Resour. Conserv. Recycl.,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85186448959
874,Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....,"Kaiser, Jan (57383738200); Hernández, Marco Pé...",57383738200; 57209478009; 57563066400; 5721506...,An agent-based approach for energy-efficient s...,2024,Engineering Applications of Artificial Intelli...,127,NaN,107198,NaN,...,NaN,EAAIE,NaN,English,Eng Appl Artif Intell,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85172726735

In [5]:
import os

print(os.getcwd())

C:\Users\Naquiuzzaman\Desktop\DATA SCIENCE\Pandas Advance ,Plotly Basics

In [6]:
import os

print(os.listdir())

['.ipynb_checkpoints', 'Pandas .ipynb', 'scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv']

In [7]:
import os

print(os.getcwd())

C:\Users\Naquiuzzaman\Desktop\DATA SCIENCE\Pandas Advance ,Plotly Basics

In [8]:
import os

print("Current Working Directory:")
print(os.getcwd())

print("\nFiles in Current Folder:")
print(os.listdir())

Current Working Directory:
C:\Users\Naquiuzzaman\Desktop\DATA SCIENCE\Pandas Advance ,Plotly Basics

Files in Current Folder:
['.ipynb_checkpoints', 'Pandas .ipynb', 'scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv']

In [9]:
import os

folder = r"C:\Users\Naquiuzzaman\Desktop\DATA SCIENCE\Pandas Advance ,Plotly Basics"

print("Folder exists:", os.path.exists(folder))

if os.path.exists(folder):
    for file in os.listdir(folder):
        if file.lower().endswith(".csv"):
            print(file)

Folder exists: True
scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv

In [10]:
import pandas as pd

df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv")

df.head()

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,NaN,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,NaN,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,979-833159409-1,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589

In [11]:
df = pd.read_csv("D:\submission.csv")

In [12]:
df.head()

,case_id,report
0,00320399-b3ed-447c-be07-a3e3b9af6e2e,FINDINGS: No extraluminal free air is seen.\nL...
1,01b1c9ab-800b-4963-b11d-9d503952e57c,FINDINGS: Mild lower lumbar facet degenerative...
2,02aae38a-088b-4cae-bfdc-f0fb38da565d,"FINDINGS: degen chnges , mild scoliosis convex..."
3,045ea333-6d30-4edf-9d33-8ed3feb0772d,"FINDINGS: At L1-L2, mild diffuse disc bulge is..."
4,06ef946f-5b3b-4b7c-a64f-58c184dca4e6,FINDINGS: Glenohumeral alignment is maintained...

In [13]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv",header = None)

df.head()

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
1,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328
2,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,NaN,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038
3,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,NaN,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114
4,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,979-833159409-1,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358

In [14]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv",skiprows=3)

df.head()

,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60609808300); Hu, Jiabei (60077617800); Yang, Yang (58157084900)",57219867444; 60609808300; 60077617800; 58157084900,Multi-agent reinforcement learning for competitive-cooperative inter-city water resources allocation: a dynamic strategy optimization framework,2026,Journal of Hydrology,677,Unnamed: 7,135782,Unnamed: 9,...,Unnamed: 35,JHYDA,Unnamed: 37,English,J. Hydrol.,Article,Final,Unnamed: 42,Scopus,2-s2.0-105040726114
0,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,979-833159409-1,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358
1,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589
2,Michael M.S.M.; Jeyaraj P.R.,"Michael, Mary Sumitha Maria (60173212300); Jey...",60173212300; 56285133000,Sustainability in smart buildings by holistic ...,2025,Journal of Renewable and Sustainable Energy,17,6,065102,NaN,...,NaN,NaN,NaN,English,J. Renewable Sustainable Energy,Article,Final,NaN,Scopus,2-s2.0-105025710582
3,Sirdar A.; Habis H.A.; Brahimi T.,"Sirdar, Abdulsalam (60744096500); Habis, Houss...",60744096500; 60744096600; 60079397700,Human-Machine Dynamics in Unified Medical File...,2026,23rd International Learning and Technology Con...,NaN,NaN,NaN,190,...,979-831953160-5,NaN,NaN,English,Int. Learn. Technol. Conf.: Twin Minds: Agenti...,Conference paper,Final,NaN,Scopus,2-s2.0-105044873430
4,Man Y.; Zhang H.; Shu P.,"Man, Yi (60631410400); Zhang, Hanhan (60645569...",60631410400; 60645569700; 58734639400,Proactive health oriented residential floor pl...,2026,Developments in the Built Environment,26,NaN,100934,NaN,...,NaN,NaN,NaN,English,Dev. Built. Environ.,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105039827271

In [15]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv",usecols = ["Authors", "Author full names"])

df.head()

,Authors,Author full names
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103..."
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz..."
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60..."
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57..."
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat..."

In [16]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv")

df.head()

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,NaN,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,NaN,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,979-833159409-1,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589

In [17]:
# datafrane >> table

In [18]:
# Dta structure 
# one column >> this is series
# 2 dimensional in nature (rows and columns ) >> dataframe

In [19]:
df

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,NaN,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,NaN,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,979-833159409-1,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,Andrew K.; Zia A.; Rizzo D.,"Andrew, Kevin (59264606600); Zia, Asim (572234...",59264606600; 57223446194; 7005922424,Integrating Deep Reinforcement Learning into A...,2024,Lecture Notes in Networks and Systems,1066 LNNS,NaN,NaN,221,...,978-303166427-4,NaN,NaN,English,Lect. Notes Networks Syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85201106911
871,Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.,"Tew, Yishen (58700122400); Fu, Ling (577214082...",58700122400; 57721408200; 59081900100; 5772168...,Construction of Knowledge Graph for Material a...,2024,Energy Proceedings,44,NaN,NaN,NaN,...,NaN,NaN,NaN,English,Energy. Proc.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85190366728
872,Ullah K.M.; Oladosu G.A.; Crooks A.,"Ullah, Kazi Masel (56239217200); Oladosu, Gbad...",56239217200; 6602587328; 25521036800,Evaluating the incentive for soil organic carb...,2023,Journal of Environmental Management,348,NaN,119418,NaN,...,NaN,JEVMA,37871549.0,English,J. Environ. Manage.,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-85174450993
873,Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...,"Shen, Weiwei (57346991900); Marín Del Valle, T...",57346991900; 57226063061; 57196091876; 5719626...,Scenario analyses of mariculture expansion in ...,2024,"Resources, Conservation and Recycling",204,NaN,107508,NaN,...,NaN,RCREE,NaN,English,Resour. Conserv. Recycl.,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85186448959
874,Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....,"Kaiser, Jan (57383738200); Hernández, Marco Pé...",57383738200; 57209478009; 57563066400; 5721506...,An agent-based approach for energy-efficient s...,2024,Engineering Applications of Artificial Intelli...,127,NaN,107198,NaN,...,NaN,EAAIE,NaN,English,Eng Appl Artif Intell,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85172726735

In [20]:
type(df)

pandas.DataFrame

In [21]:
df ["PubMed ID"]

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
          ...
870           NaN
871           NaN
872    37871549.0
873           NaN
874           NaN
Name: PubMed ID, Length: 875, dtype: float64

In [22]:
type(df ["PubMed ID"])

pandas.Series

In [23]:
#multiple series makes a draftframe

In [24]:
l = [1,2,3,4,5]
s = pd.Series(l)

In [25]:
type (s)

pandas.Series

In [26]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [27]:
d = pd.Series([100,300,500,700,900], index = ["Md Naquiuzzaman", "Marhaba", "Marushat","Queen","King"])

In [28]:
d

Md Naquiuzzaman    100
Marhaba            300
Marushat           500
Queen              700
King               900
dtype: int64

In [29]:
d ["King"]

np.int64(900)

In [30]:
d.reset_index(drop = True , inplace = True) #drop = True  >> drop the original index
#inplace True >> modify original Series

In [31]:
d

0    100
1    300
2    500
3    700
4    900
dtype: int64

In [32]:
df.shape # This will give you rows and column

(875, 45)

In [33]:
df.columns

Index(['Authors', 'Author full names', 'Author(s) ID', 'Title', 'Year',
       'Source title', 'Volume', 'Issue', 'Art. No.', 'Page start', 'Page end',
       'Cited by', 'DOI', 'Link', 'Affiliations', 'Authors with affiliations',
       'Abstract', 'Author Keywords', 'Index Keywords',
       'Molecular Sequence Numbers', 'Chemicals/CAS', 'Tradenames',
       'Manufacturers', 'Funding Details', 'Funding Texts', 'References',
       'Correspondence Address', 'Editors', 'Publisher', 'Sponsors',
       'Conference name', 'Conference date', 'Conference location',
       'Conference code', 'ISSN', 'ISBN', 'CODEN', 'PubMed ID',
       'Language of Original Document', 'Abbreviated Source Title',
       'Document Type', 'Publication Stage', 'Open Access', 'Source', 'EID'],
      dtype='str')

# Advance

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 875 entries, 0 to 874
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Authors                        875 non-null    str
 1   Author full names              875 non-null    str
 2   Author(s) ID                   875 non-null    str
 3   Title                          875 non-null    str
 4   Year                           875 non-null    int64
 5   Source title                   875 non-null    str
 6   Volume                         586 non-null    str
 7   Issue                          229 non-null    str
 8   Art. No.                       334 non-null    str
 9   Page start                     404 non-null    str
 10  Page end                       404 non-null    str
 11  Cited by                       875 non-null    int64
 12  DOI                            835 non-null    str
 13  Link                           875 non-null    str
 14  Affiliations                   874 non-null    str
 15  Authors with affiliations      874 non-null    str
 16  Abstract                       875 non-null    str
 17  Author Keywords                828 non-null    str
 18  Index Keywords                 805 non-null    str
 19  Molecular Sequence Numbers     0 non-null      float64
 20  Chemicals/CAS                  11 non-null     str
 21  Tradenames                     2 non-null      str
 22  Manufacturers                  1 non-null      str
 23  Funding Details                428 non-null    str
 24  Funding Texts                  426 non-null    str
 25  References                     873 non-null    str
 26  Correspondence Address         730 non-null    str
 27  Editors                        197 non-null    str
 28  Publisher                      875 non-null    str
 29  Sponsors                       134 non-null    str
 30  Conference name                412 non-null    str
 31  Conference date                412 non-null    str
 32  Conference location            412 non-null    str
 33  Conference code                412 non-null    float64
 34  ISSN                           638 non-null    str
 35  ISBN                           362 non-null    str
 36  CODEN                          178 non-null    str
 37  PubMed ID                      34 non-null     float64
 38  Language of Original Document  875 non-null    str
 39  Abbreviated Source Title       875 non-null    str
 40  Document Type                  875 non-null    str
 41  Publication Stage              875 non-null    str
 42  Open Access                    321 non-null    str
 43  Source                         875 non-null    str
 44  EID                            875 non-null    str
dtypes: float64(3), int64(2), str(40)
memory usage: 9.2 MB

In [35]:
df.dtypes

Authors                              str
Author full names                    str
Author(s) ID                         str
Title                                str
Year                               int64
Source title                         str
Volume                               str
Issue                                str
Art. No.                             str
Page start                           str
Page end                             str
Cited by                           int64
DOI                                  str
Link                                 str
Affiliations                         str
Authors with affiliations            str
Abstract                             str
Author Keywords                      str
Index Keywords                       str
Molecular Sequence Numbers       float64
Chemicals/CAS                        str
Tradenames                           str
Manufacturers                        str
Funding Details                      str
Funding Texts                        str
References                           str
Correspondence Address               str
Editors                              str
Publisher                            str
Sponsors                             str
Conference name                      str
Conference date                      str
Conference location                  str
Conference code                  float64
ISSN                                 str
ISBN                                 str
CODEN                                str
PubMed ID                        float64
Language of Original Document        str
Abbreviated Source Title             str
Document Type                        str
Publication Stage                    str
Open Access                          str
Source                               str
EID                                  str
dtype: object

In [36]:
df["Authors"]

0                      Tou Y.; Nagamatsu A.; Watanabe C.
1                   Guzmán E.; Andrés B.; Torres-Polo M.
2                        Yuan M.; Guo X.; Hu J.; Yang Y.
3                                 Alzu'Bi S.; Mughaid A.
4                           Chootongchai S.; Maneerat P.
                             ...
870                          Andrew K.; Zia A.; Rizzo D.
871         Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.
872                  Ullah K.M.; Oladosu G.A.; Crooks A.
873    Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...
874    Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....
Name: Authors, Length: 875, dtype: str

In [37]:
df[["Authors","Author full names"]]

,Authors,Author full names
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103..."
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz..."
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60..."
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57..."
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat..."
...,...,...
870,Andrew K.; Zia A.; Rizzo D.,"Andrew, Kevin (59264606600); Zia, Asim (572234..."
871,Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.,"Tew, Yishen (58700122400); Fu, Ling (577214082..."
872,Ullah K.M.; Oladosu G.A.; Crooks A.,"Ullah, Kazi Masel (56239217200); Oladosu, Gbad..."
873,Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...,"Shen, Weiwei (57346991900); Marín Del Valle, T..."
874,Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....,"Kaiser, Jan (57383738200); Hernández, Marco Pé..."

In [38]:
list(df["Author full names"])

['Tou, Yuji (6603292302); Nagamatsu, Akira (7103054512); Watanabe, Chihiro (55619319799)',
 'Guzmán, Eduardo (57217008411); Andrés, Beatriz (55508042400); Torres-Polo, Marta (57890088200)',
 'Yuan, Mingkang (57219867444); Guo, Xueling (60609808300); Hu, Jiabei (60077617800); Yang, Yang (58157084900)',
 "Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57209223613)",
 'Chootongchai, Suparoek (56857620000); Maneerat, Paralee (57191034244)',
 'Michael, Mary Sumitha Maria (60173212300); Jeyaraj, Pandia Rajan (56285133000)',
 'Sirdar, Abdulsalam (60744096500); Habis, Houssam A. (60744096600); Brahimi, Tayeb (60079397700)',
 'Man, Yi (60631410400); Zhang, Hanhan (60645569700); Shu, Ping (58734639400)',
 'Araña, Jorge E. (7005207170)',
 'Sun, Chenxiao (57802651900); Liu, Yitong (56410498000); Deng, Juan (60715612600); Chen, Tianjiao (60716999000); Yang, Hongwen (7406566589)',
 'Zhang, Zi-Qi (57203273373); Li, Jia-Qu (60514697500); Huang, Tong (60115574600); Li, Xiao-Wei (59959931200); Qian, Bin (56383438700); Hu, Rong (55014288900)',
 'Moore, Lewis (60741643100); Olszewska, Joanna (55623356800)',
 'Reddy, Venkat (57220973447); Li, Dahui (13805539900)',
 'Knáb, István Gellért (59170743700); Stankovics, Márk (60819024400); Kővári, Bálint (57220275513); Gáspár, Péter (57191521633); Palkovics, László (7004638104)',
 'Yolles, Maurice (6701448613); Chiolerio, Alessandro (57202563714)',
 'Yang, Yingxuan (58521198700); Peng, Qiuying (57701533800); Wang, Jun (59945975500); Wen, Ying (57193525684); Zhang, Weinan (56108513500)',
 'Thomaidis, Ioannis T. (58921377200); Giannopoulos, Panagiotis G. (57225456229); Dasaklis, Thomas K. (27267526900)',
 'LIU, Weifeng (57489578200); WANG, Jing (60641110900); WANG, Zhihua (15924681100); YU, Hongbing (60641111000); TANG, Xiaodong (60641611100); HE, Guangyu (26643277800)',
 'Mamidala, Vijaykumar (59401305800); Yalla, Rama Krishna Mani Kanta (59400488900); Ganesan, Thirusubramanian (60626287100); Devarajan, Mohanarangan Veerapperumal (58693818500); Yallamelli, Akhil Raj Gaius (59369976600); Antonidoss, A. (55027419000)',
 'Dingil, Ali Enes (57205075810); Pereira, Andre Maia (57195392015); Přibyl, Ondrej (6506161920); Vorel, Jakub (56118447400)',
 'Zhang, Zeren (57750793700); Zhang, Bin (55605769193); Zhou, Guangchong (57751569100); Li, Dapeng (59284070100); Xu, Zhiwei (59046535100); Fan, Guoliang (55810655800)',
 'Ali, Najma Imtiaz (57201114679); Jamali, Aadil (58990793000); Brohi, Imtiaz Ali (57193329783); Jhanjhi, Noor Zaman (36088700700); Kasmuri, Emaliana (35146188400)',
 'Sandeep, Ashen (60387969700); Jayarathna, Sithum (60388529200); Sandaruwan, Sunera (60388803200); Samarappuli, Venura (60388666000); Meedeniya, Dulani (24779848000); Perera, Charith (55293491900)',
 'Dragomir, Otilia Elena (26537327000); Dragomir, Florin (26537264300)',
 'Blancoc, Luis (60734638900); Vaca-Rubio, Cristian J. (57210861374); Baranda, Jorge (25824713000); Javed, Farhana (57202513431); Via, Selva (26422672800); Zeydan, Engin (24315322700); Contreras, Luis M. (55819446800); Velazquez, Javier (25825852500); Kedar, Gil (56971257400); Dvir, Efi (60734397900); Antonio, Gianluca Rizzo (59995489800); Buzcu, Berk (57983933700); Serrano, Maria A. (57188687546); Antonopoulos, Angelos (35316741000); Kibalya, Godfrey (55569216500); Haxhibeqiri, Jetmir (57189044377); Maglogiannis, Vasilis (55588516400); Naudts, Dries (55974766700); Hoebeke, Jeroen (8914771300); De Cola, Tomaso (10739364500); Kirubakaran, Balaji (57891792800); Spantideas, Sotirios (56549912200); Giannopoulos, Anastasios (57218483521); Trakadas, Panagiotis (6603036390); Koumaras, Harilaos (17434625400); Plastras, Stefanos (58420414400); Piemonti, Alice (59995300100); Cianchini, Vito (59995117900); Amatetti, Carla (57221852551); De Filippo, Bruno (59237852500); Gao, Zefu (60734443600); Kryszkiewicz, Pawel (55322491600); Pakula, Marcin (60617579200); Kulacz, Lukasz (57195334271); Placzkiewicz, Pawel (59508977200); Kliks, Adrian (26325609500); Pagin, Matteo (57219433387); Wang, Hua (60734683900); Cherrared, Sihem (57203001803); Djaidja, Taki (57886748600)',
 'Hsieh, Fu-Shiung (7102108552)',
 'Eslahi, Mojtaba (57193666092); Farazdaghi, Elham (57193155616); Sammuneh, Muhammad Ali (57203369964); Meouche, Rani El (41961023000)',
 'Sarathkumar, D. (56405627300); Maheswari, P. (59739341100); Manivel, Murugesan (58186962400); Jayakumar, T. (57215901834); Sivakumar, R. (59513927000); Parrthipan, B.K. (57234172500)',
 'Vasu, Sujo (57222103674); Kumar, P. Ramesh (57220737996); Jasmin, E.A. (26423009700); Mini, V. (36554792800)',
 'Gao, Xi (59392459000); Gao, Yicong (23088144600); Bai, Congcong (57579516300); Yang, Chengcheng (58402564600); Rong, Donglei (57219311203); Yao, Wenbin (57205546239); Gao, Kun (57204201059); Jin, Sheng (55214223800)',
 'Wei, Xingchen (58289340700); Su, Jinshu (7401681903); Song, Congxi (57207110543); Xia, Yusheng (57190809256)',
 'Brunner, Manuel (57191171071); Thienemann, Ann-Kristin (59416576600); Tripathi, Shailesh (57197323715); Bachmann, Nadine (57468425200); Tüzün, Alican (58620691700); Pöchtrager, Sebastian (58976784700); Warnau, Judith (60652693400); Jodlbauer, Herbert (12763825700)',
 'Gao, Jing (57212121923); Gong, Jian (55040853200); Schwarz, Nina (23986260300); Sliuzas, Richard (23006851900)',
 'Aylak, Batin Latif (56313342700)',
 'Pop-Cohuţ, Ioana-Crina (57226612127)',
 'de Alencar, Tatiana Silva (56237113500); Zaina, Luciana (6506081735)',
 'Niu, Xuezhi (59193807300); Barajas, Natalia Calvo (60652717000); Broo, Didem Gürdür (55648593700)',
 'Ismail, Sadia (57195977685); Alharbi, Abeer A.K. (59076056000); Zahra, Syeda Rabail (57190346426); Khattak, Amin Khan (60805221000); Mazhar, Tehseen (57219034600); Saudagar, Abdul Khader Jilani (56166431300); Hamam, Habib (7004762599); Khan, Muhammad Amir (56132357300)',
 'Wang, Yunan (59369798800); Yang, Huicong (60201934200); Leng, Jiaxu (60200949800); Liu, Kairui (60201764100)',
 'Zhang, Zhihan (58285529100)',
 'Pu, Yu (60620078700); Yang, Jianhui (60619863500)',
 'Aljijakli, Marwan (59791986700); Akkari, Nadine (23007535500)',
 'Nasiri, Amir Reza (58928078000); Kerachian, Reza (55975065200); Shahangian, Seyyed Ahmadreza (57223132911); Kamali, Fardin (57878592900); Najafi Dehjalali, Amirhossein (60242868000)',
 'Sakthivel, Thilagavathy (60224090500); Murugesan, Rajasekar (57188815838); Gopalan, Anitha (57924408700)',
 'Kundu, Shakti (54420380700); Ninoria, Shalini Zanzote (57216588097); Chaturvedi, Ravi Prakash (57208126664); Mishra, Annu (57267170400); Agrawal, Akshat (57213441821); Batra, Reenu (57422585400); Dubale, Mitiku (57684170000); Hashmi, Arshad (57222735849)',
 'Ying, Megan Y. (60230006500); Grandi, Daniele (57192710469); Groom, Allin (59148313300); McComb, Christopher (56400780700)',
 'Zouein, Pierrette (6602355613); Amine, Amir (60079019600); Amine, Raghad (60092818100); Jammoul, Ali (60093052000); Nashi, Mounir (60093406600); Jifetjian, Vanessa (60093406700); Smayra, Marilyn (60093052100)',
 'Friedmann, Danny (60787013900)',
 'Zykov, Sergey V. (36146486900)',
 'Bistaffa, Filippo (55516740200); Oliveira, Sergio Calo (58085284800)',
 'Naug, Avisek (57188968713); Guillen, Antonio (58248731700); Kumar, Vineet (57224775941); Greenwood, Scott (60233160100); Brewer, Wesley (57207843034); Ghorbanpour, Sahand (25641507600); Babu, Ashwin Ramesh (57192372079); Gundecha, Vineet (57219621443); Gutierrez, Ricardo Luna (57211751618); Sarkar, Soumyendu (57899989600)',
 'Trasculescu, Andrei-Costin (57220990764); Resceanu, Ionut-Cristian (16031983600); Padeanu, Ionut-Ovidiu (59960782000); Cismaru, Stefan-Irinel (57203967944); Petcu, Florina-Luminita (59961568500); Roibu, Horatiu (57202402592); Dita, Florin-Alexandru (59466666900); Iftimiciuc, Ionut-Nicusor (59960998500); Bizdoaca, Nicu-George (6506215184)',
 'Sumalatha, A. (58976489600); Sabri, Mohammad Omar (57197842391); Kumar, J. Sunil (60383479800); Vijayanandh, T. (56623137900); Lalitha, J. (60546713600); Shanmugam, N. (60547359600)',
 'Hoang, Thong (57210914382); Klymenko, Mykhailo (14056245800); Xu, Xiwei (55706225900); Pan, Shidong (57477785900); Ding, Yi (60539352800); Tang, Xushuo (58262412500); Yang, Zhengyi (57209984247); Shi, Jieke (57225119268); Lo, David (35269388000)',
 'Guo, Yujie (60099075100)',
 'Liang, Chao (59773702000); Xv, Hanyi (60629804300); Wang, Hong (60628891600); Xi, Bingyang (59773475300); Mao, Mengling (60628666200); Liu, Siyu (60629804400)',
 'Zohaib, Muhammad (57193709759); Akbar, Muhammad Azeem (57200183503); Hyrynsalmi, Sami (50361307000)',
 'Wu, Yuzhou (59938785200); Wu, Mingyang (59939197400); Deng, Peng (57190759273); Liu, Di (58678353000); Li, Kang (57445059900); Zhao, Yong (59550864400); Yin, Rong (57219200711)',
 'Jiang, Yuan-Hao (58399698000); Chen, Zi-Wei (58694658700); Zhao, Cong (59561098700); Tang, Kezong (35759841700); Duan, Jicong (58565855300); Zhou, Yizhou (59213890100)',
 'Nandhlal, Kavisha (60687020100); Kabanda, Gabriel (25723410900)',
 'Chen, Ruoxi (60413325900); Wang, Peipei (57216413976); Zheng, Xinqi (16064941200); Rao, Xinrui (60413205500); Zhang, Xiaoyuan (57729180000); Wang, Wenqi (60413027200)',
 'Cheng, Mingjun (57354963900); Jin, Hong (60199776600); Zhao, Qinfeng (57459988700); Wang, Yurun (60199304900); Wu, Yanxi (60200408100); Huang, Shan (56140282200); Yue, Wenze (8721631200)',
 'Hu, Kun (60240090200); Yao, Xifan (24385945500); Qiao, Fei (7005620707); Shen, Weiming (60423877700); Wu, Hongxing (7405584772); Yang, Wenyu (60423263700)',
 'He, Tingting (59374734700); Goh, Hui Hwang (24075809200); Pang, Wai Leong (8701196600); Phang, Swee King (36519608700); Wen, Lingyu (60413147700); Zhong, Xiaowen (60413147800)',
 'Kumar, P. Santhosh (57199976562); Pankajam, A. (57729480300); Veeraiah, Vivek (55151379400); Gharat, Adveta (57912515400); Mamatha, G. (35146519000); Roy, Devika Rani (58136306700); Gupta, Ankur (57215604870); Rajitha, N. (57773275400)',
 'Postorino, Maria Nadia (6701783667); Sarné, Giuseppe M.L. (6505830755)',
 'Dallavalle, Silvia (57849642500); Ribeiro, Luiz Ricardo Brito (59322197700); Moreira, Sérgio Adriany Santos (59228962500)',
 'Samoylova, Nadezhda A. (57202819286); Moskalenko, Igor V. (58707637000)',
 'Deng, Changhe (60017992500); Fang, Xi (37013171200)',
 'Pataranutaporn, Pat (56983058400); Doudkin, Alexander (59707675900); Maes, Pattie (56268463300)',
 'Al Hasan, Maram (59701405800); Kashef, Ayat (60777299200); Mohsen, Wissal (59758575600); Khan, Asma Gul Yousaf (60777902000); Alomari, Maryam (60777299300); Aishan, Hafsa (60126742300)',
 'Aguiar, Vinícius Alboneti (60614914200); Amorim, Leonardo Afonso (57210090261); Novais, Artur Matos Andrade (60614527100); De Jesus, Thiago Pedroso (60614431300); Da Silva Soares, Anderson (23391741100); De Oliveira, Sávio Salvarino Teles (56459632300)',
 'Coronado, Enrique (57188864138)',
 'Kim, Jiin (59193998100); Shin, Byeongjun (59979785200); Chung, Jinha (57699403200); Rhu, Minsoo (55813564600)',
 'Zhang, Jing (58236246600); Chen, Zhe (57207957994); Xiao, Ziwei (58759154600); Xu, Kan (57478338900); Ma, Tianyou (58235792400); Xiao, Fu (60235891300); Tse, Lok Him (60097621700); Cheung, Man Chit (60722293400); Lau, Ka Tai (59263197000)',
 'Arvindkumar, S. (59523705700); Ragunanthan (60238921700); Pitchaimani, Kalpana (57224479487)',
 'Akhadkar, Lavesh (60731095800); Thakre, Kalpana (37102832900); Kulkarni, Aditya (60731611900); Kadam, Parth (60731612000); Damle, Varun (60730888800)',
 'Shqair, Maram (56382413200); Sweis, Karam (59912323200); Dawkassab, Haya (59911683300); Altarazi, Safwan (24342677300); Mykoniatis, Konstantinos (55835108800)',
 'Wang, Reen-Cheng (7405335651); Hsieh, Ming-Che (55436431000); Lai, Liang-Chun (60351394300)',
 'Alvarez Castro, David (57226610120); Ford, Alistair (56246892400); Palacin, Roberto (16176000900); James, Philip (7402640970); Ziemke, Dominik (57189469071)',
 'Yls, Julius (60328311300); Yeoh, Kok Cheow (36456485100)',
 'Tao, Ming (27467918600); Su, Lingfeng (59696962700); Xie, Renping (56039766800); Dai, Hong-Ning (55602606800); Zhou, Xiaokang (55514932700)',
 'Zhang, Xugang (36722985700); Liu, Chuang (60026776800); Yue, Yong (60026502300); Gong, Qingshan (51664924200); Ma, Feng (57191358954); Wang, Yan (56274770600)',
 'Liu, Zebin (57737865900); Zhang, Xiaoheng (57221677226); Lv, Hui (60232405200); Shen, Lei (60232280200)',
 'Zhang, Yinuo (60819495500); Jia, Xing (60818701900); Wang, Zihui (60818702000); Zhou, Zhiyi (60819297600); Liu, Boyu (60819097800)',
 'Basingab, Mohammed Salem (57197831724)',
 'Rabbi, Mohammad Fazle (57219488464)',
 'Luo, Jinliang (58701805600)',
 'Liang, Zongbao (8970392500); Wang, Shichao (57202036272); Cui, Hongmei (57201072985); Feng, Junli (60241824300)',
 'Caprioli, Caterina (57209981157)',
 'Patnaik, Deepti (57222665793); Kadao, Anjali Krushna (59760802600)',
 'Lin, Fangkun (60250017000); Luo, Zhipeng (58905504100); Ma, Binyu (60646881300); Zhang, Zhiyu (60009408900); Liu, Kaiyan (60646629200); Yu, Xin (58732480000); Xu, Boyan (57211539035); Zeng, Huabin (57189357749)',
 'Bai, Yunhao (58616462200); Geng, Bing (57211018139); Yan, Hexiang (56495970700); Tao, Tao (57225802582); Hao, Jingkai (60284111800); Xin, Kunlun (16023519100)',
 'Himri, Khadija (60340267900); Joiron, Céline (6508364733); Kodad, Mohcine (57163906700)',
 'Raghupathi, Wullianallur (6603002503); Raghupathi, Viju (26032307400)',
 'Adar, Ömer (59407751400); Cihan, Onur (35776006100)',
 'Latha, Challa Madhavi (57205080757); Alvarado-Mentado, Matias (57201901936)',
 'Xin, Jie (57373621500); Zhang, Hangqi (60497458400)',
 'Sanogo, Kader (57765902700); Masmoudi, Malek (54382267200); Mekhalef Benhafssa, Abdelkader (57118277000); Sahnoun, M’hammed (37662006000)',
 'Wang, Shuping (57211559954); Li, Changhao (57820526900); Cheng, Yifeng (59635595400); Zhou, Xinyue (60256849900); Zhang, Weixin (58990983900); Cao, Yuancheng (56979443300); Cheng, Qi (57040433100)',
 'Li, Yue (57314343500); Hu, Min (58137072100); Chen, Zhijun (57195804911); Han, Yufei (60405086200); Ren, Dongyang (56706869000); Xu, Xu (55844396600); Xiong, Yunwu (14040898300); Huang, Quanzhong (57204320881); Huang, Guanhua (57040238000)',
 'Rajman, Ridhima (60149200400); Kaur, Kushalpreet (60096929500); Bhuyan, Ajatray Swagat (58194084500)',
 'Kozub, Vladyslav (59146874800); Bataiev, Sergii (59244852500); Shybko, Oksana (57203000408); Sikora, Yaroslava (57224617763); Voloshchuk, Serhii (59547490900)',
 'Bakhtadze, Natalia (6603467848); Dozortsev, Victor (6603105788); Vlasov, Artem (60354581600); Koroleva, Mariya (60353866100); Anikin, Maxim (60354581700)',
 'López-Goyez, Juan P. (59426908800); Mina, Jorge (60428420000); Arcos, Georgina (57218311944); Miranda, Jorge (60428815200)',
 'Xiao, Zixuan (59949246700); Ma, Jun (56703806400); Zhang, Siwei (58314834000)',
 'Shah, Aneri (59715772200); Modi, Krish (60159606600); Soni, Ansh (60159549000); Doshi, Nishant (37050599100)',
 'Liu, Jia’an (60160146500); Chu, Chu (59551914900); Zhao, Yilin (58306860800); Aoki, Goshi (58072734200); Xiao, Zhiqing (57670029100)',
 'Abdulameer, Susan Sabah (57209466700); Ibrahim, Yousif Munadhil (57209332374)',
 'Zarreh, Mobin (58583793300); Grogan, Paul T. (36620196300)',
 'Su, Dandan (57226809140); Neusypin, K.A. (6602995907); Dong, Ge (57192645414)',
 'Beena, B.M. (56538442100); Manideep, Thotapalli Sri Surya (57200213624); Saragadam, Sneha (59491597100); Rathi, Sailesh (60571210700); Ramesh, Ramaswamy (7201897779); Holimath, Vijay (18934957100)',
 'Ambrosino, Erica (60810115500); Andreotti, Amedeo (35564985300); Aruta, Marco (59409918300); Ballot, Gabriel (57798435300); Capone, Andrea (60498680500); de Notaristefani di Vastogirardi, Giulio (57170930000); Ferrigno, Sara (60810990600); Improta, Francesco (60215933000); Listone, Ciro (59966062700); Malvone, Vadim (57009152700); Maubert, Bastien (35092930800); Nappi, Floriana (60810698500); Romano, Salvatore (59967608600); Murano, Aniello (14061017200)',
 'Liu, Junbei (57424299600); Zhuge, Chengxiang (54953547900); Tang, Justin Hayse Chiwing G. (57424446600); Meng, Meng (60042285000); Zhang, Jie (60041650000)',
 'Du, Jinhao (58777360900); Chen, Yarong (36093728000); Mumtaz, Jabir (57204833663); Alkaabneh, Faisal (55317855100); Ji, Ziyang (59712966700); Minhas, Kaynat Afzal (58891068800)',
 'Tabassum, Shaira (57215310225); Kiss, Gabriel Hanssen (34978601700); Verma, Sachin (57203340729); Raja, Kiran (57188866050); Lindseth, Frank (6602262992)',
 'Syauqi, Ahmad (57608664200); Ramdani, Akmal (60705493300); Lim, Hankwon (14019936500); Andika, Riezqa (56197952200)',
 'Majumdar, Swarnamouli (57782341500); Awasthi, Anjali (57203055159)',
 'Abuselidze, George (57204928171); Amanova, Gulnara (56529694000); Ryskeldiyeva, Aidana (60713748300); Saduakassova, Kunsulu (57191911797)',
 'Nanoff, Tyler James (58551808100); Gonzalez Villasanti, Hugo (57192301586)',
 "Mas'udah (57204723857); Livotov, Pavel (57164768200); Kokoschko, Björn R. (57223631192); Xu, Wanyu (57355001200); Hendra, Immanuel (58499263400); Hartmann, Niklas (36606153400)",
 'Chari, Shreya K. (59705878100); Vardakas, John S. (8710803300); Ramantas, Kostas (16204223400); Verikoukis, Christos (16176716900)',
 'Calderón, Christian (59682237000); Martí, Pasqual (57218267377); Jordán, Jaume (55421766500); Palanca, Javier (23392934000); Julian, Vicente (6602206677)',
 'Pritul, Toufiq Imroze (60728544500); Ratul, Qudrat E Alahy (57468684500)',
 'Abdelnaby, Khalil M. (57209913140); Al-Husainy, Mohammed A. F. (14832362400); Alhawarat, Mohammad O. (57148556900); Rohaim, Mohamed A. (60583551800); Assar, Khairy M. (60582456000)',
 'Pareek, Sweta (60752654900); Kalaneya, Chetany (60577042900); Kumawat, Rohit (60577971400); Pareek, Shilpa (57193061543); Sharma, Yashaskar (60752655000)',
 'Fonseca i Casas, Pau (55533533700); Pi i Palomes, Xavier (57226315126)',
 'Yordanova, Zornitsa (57200724991); Nozari, Hamed (57210320748)',
 'Fagbohun, Oluwole (58932574800); Yashwanth, Sai (59733177500); Akintola, Akinyemi Sadeeq (59728892400); Wurola, Ifeoluwa (59733355200); Shittu, Lanre (59733177600); Inyang, Aniema (59733590900); Odubola, Oluwatimilehin (59676651100); Offia, Udodirim (59733774800); Olanrewaju, Said (59732638100); Toluwaleke, Ogidan (59732821100); Abutu, Ilemona (59732638200); Akinbolaji, Taiwo (59733902800)',
 'Xie, Weihong (60681798000); Yu, Juan (59524626700); Chen, Rongkang (59346430700); Li, Zhongshun (58151055800); Zheng, Diwen (57884657800)',
 'Majewska, Justyna (56519892800); Niezgoda, Agnieszka (6602508662); Truskolaski, Szymon (55849635900)',
 'Mishra, Tathastu (60765680900); Sinha, Sapna (57195607530)',
 'Kęsy, Marcin (57225051099); Britchenko, Igor (56891643900)',
 'Torgbi Agbemabiese, William (60370243900)',
 'Som, Shreya (59954368200); Patil, Samruddhi (60765116900); Pervin, Nargis (36918997800)',
 'Joshi, Varun (60166038700); Kothari, Nikita (60166893300); Kumar, Lav (60166985100)',
 'Creti, Veronica (60614920800); Rucco, Chiara (57773449100); Stefano, Alessandro (60615011500); Zampino, Francesca (58111773800); Saad, Motaz (56494148300); Longo, Antonella (57209449951); Ardebili, Ali Aghazadeh (57216462967)',
 'Parker, Laci (59710234200); Allison, Mark (55265013200)',
 'Nguyen, Bichlien H (60696903900)',
 'Anh, Tran Thi Quynh (59955961200); Nguyen-Huu, Tri (14632281000); Nguyen-Ngoc, Doanh (37018666500)',
 'Osika, Zuzanna (58569005900); Rădulescu, Roxana (57190129123); Zatarain-Salazar, Jazmin (58036549100); Oliehoek, Frans A. (15043050300); Murukannaiah, Pradeep K. (26032199400)',
 'Mariaraj, R. Jeffrey (60422780200); Lobo, Ronan (60422067900); Gowda, Maurya P (60422206700)',
 'Jaswal, Navneet (60606773200); Yadav, Bharat (60611594300); Kadian, Gagan (60611218500); Khanna, Chirag (60611687000)',
 'Gavai, Anand K. (35366319900); Meuwissen, Miranda P.M. (7003942968)',
 'Lee, Young-Chan (26662005200); Yang, Chuyu (60787965000)',
 'Krupp, Lars (57210566952); Geißler, Daniel (58183401300); Banwari, Vishal (59956340100); Lukowicz, Paul (6701557151); Karolus, Jakob (56644671700)',

In [39]:
print(list)

<class 'list'>

In [40]:
list(df["Author full names"])

['Tou, Yuji (6603292302); Nagamatsu, Akira (7103054512); Watanabe, Chihiro (55619319799)',
 'Guzmán, Eduardo (57217008411); Andrés, Beatriz (55508042400); Torres-Polo, Marta (57890088200)',
 'Yuan, Mingkang (57219867444); Guo, Xueling (60609808300); Hu, Jiabei (60077617800); Yang, Yang (58157084900)',
 "Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57209223613)",
 'Chootongchai, Suparoek (56857620000); Maneerat, Paralee (57191034244)',
 'Michael, Mary Sumitha Maria (60173212300); Jeyaraj, Pandia Rajan (56285133000)',
 'Sirdar, Abdulsalam (60744096500); Habis, Houssam A. (60744096600); Brahimi, Tayeb (60079397700)',
 'Man, Yi (60631410400); Zhang, Hanhan (60645569700); Shu, Ping (58734639400)',
 'Araña, Jorge E. (7005207170)',
 'Sun, Chenxiao (57802651900); Liu, Yitong (56410498000); Deng, Juan (60715612600); Chen, Tianjiao (60716999000); Yang, Hongwen (7406566589)',
 'Zhang, Zi-Qi (57203273373); Li, Jia-Qu (60514697500); Huang, Tong (60115574600); Li, Xiao-Wei (59959931200); Qian, Bin (56383438700); Hu, Rong (55014288900)',
 'Moore, Lewis (60741643100); Olszewska, Joanna (55623356800)',
 'Reddy, Venkat (57220973447); Li, Dahui (13805539900)',
 'Knáb, István Gellért (59170743700); Stankovics, Márk (60819024400); Kővári, Bálint (57220275513); Gáspár, Péter (57191521633); Palkovics, László (7004638104)',
 'Yolles, Maurice (6701448613); Chiolerio, Alessandro (57202563714)',
 'Yang, Yingxuan (58521198700); Peng, Qiuying (57701533800); Wang, Jun (59945975500); Wen, Ying (57193525684); Zhang, Weinan (56108513500)',
 'Thomaidis, Ioannis T. (58921377200); Giannopoulos, Panagiotis G. (57225456229); Dasaklis, Thomas K. (27267526900)',
 'LIU, Weifeng (57489578200); WANG, Jing (60641110900); WANG, Zhihua (15924681100); YU, Hongbing (60641111000); TANG, Xiaodong (60641611100); HE, Guangyu (26643277800)',
 'Mamidala, Vijaykumar (59401305800); Yalla, Rama Krishna Mani Kanta (59400488900); Ganesan, Thirusubramanian (60626287100); Devarajan, Mohanarangan Veerapperumal (58693818500); Yallamelli, Akhil Raj Gaius (59369976600); Antonidoss, A. (55027419000)',
 'Dingil, Ali Enes (57205075810); Pereira, Andre Maia (57195392015); Přibyl, Ondrej (6506161920); Vorel, Jakub (56118447400)',
 'Zhang, Zeren (57750793700); Zhang, Bin (55605769193); Zhou, Guangchong (57751569100); Li, Dapeng (59284070100); Xu, Zhiwei (59046535100); Fan, Guoliang (55810655800)',
 'Ali, Najma Imtiaz (57201114679); Jamali, Aadil (58990793000); Brohi, Imtiaz Ali (57193329783); Jhanjhi, Noor Zaman (36088700700); Kasmuri, Emaliana (35146188400)',
 'Sandeep, Ashen (60387969700); Jayarathna, Sithum (60388529200); Sandaruwan, Sunera (60388803200); Samarappuli, Venura (60388666000); Meedeniya, Dulani (24779848000); Perera, Charith (55293491900)',
 'Dragomir, Otilia Elena (26537327000); Dragomir, Florin (26537264300)',
 'Blancoc, Luis (60734638900); Vaca-Rubio, Cristian J. (57210861374); Baranda, Jorge (25824713000); Javed, Farhana (57202513431); Via, Selva (26422672800); Zeydan, Engin (24315322700); Contreras, Luis M. (55819446800); Velazquez, Javier (25825852500); Kedar, Gil (56971257400); Dvir, Efi (60734397900); Antonio, Gianluca Rizzo (59995489800); Buzcu, Berk (57983933700); Serrano, Maria A. (57188687546); Antonopoulos, Angelos (35316741000); Kibalya, Godfrey (55569216500); Haxhibeqiri, Jetmir (57189044377); Maglogiannis, Vasilis (55588516400); Naudts, Dries (55974766700); Hoebeke, Jeroen (8914771300); De Cola, Tomaso (10739364500); Kirubakaran, Balaji (57891792800); Spantideas, Sotirios (56549912200); Giannopoulos, Anastasios (57218483521); Trakadas, Panagiotis (6603036390); Koumaras, Harilaos (17434625400); Plastras, Stefanos (58420414400); Piemonti, Alice (59995300100); Cianchini, Vito (59995117900); Amatetti, Carla (57221852551); De Filippo, Bruno (59237852500); Gao, Zefu (60734443600); Kryszkiewicz, Pawel (55322491600); Pakula, Marcin (60617579200); Kulacz, Lukasz (57195334271); Placzkiewicz, Pawel (59508977200); Kliks, Adrian (26325609500); Pagin, Matteo (57219433387); Wang, Hua (60734683900); Cherrared, Sihem (57203001803); Djaidja, Taki (57886748600)',
 'Hsieh, Fu-Shiung (7102108552)',
 'Eslahi, Mojtaba (57193666092); Farazdaghi, Elham (57193155616); Sammuneh, Muhammad Ali (57203369964); Meouche, Rani El (41961023000)',
 'Sarathkumar, D. (56405627300); Maheswari, P. (59739341100); Manivel, Murugesan (58186962400); Jayakumar, T. (57215901834); Sivakumar, R. (59513927000); Parrthipan, B.K. (57234172500)',
 'Vasu, Sujo (57222103674); Kumar, P. Ramesh (57220737996); Jasmin, E.A. (26423009700); Mini, V. (36554792800)',
 'Gao, Xi (59392459000); Gao, Yicong (23088144600); Bai, Congcong (57579516300); Yang, Chengcheng (58402564600); Rong, Donglei (57219311203); Yao, Wenbin (57205546239); Gao, Kun (57204201059); Jin, Sheng (55214223800)',
 'Wei, Xingchen (58289340700); Su, Jinshu (7401681903); Song, Congxi (57207110543); Xia, Yusheng (57190809256)',
 'Brunner, Manuel (57191171071); Thienemann, Ann-Kristin (59416576600); Tripathi, Shailesh (57197323715); Bachmann, Nadine (57468425200); Tüzün, Alican (58620691700); Pöchtrager, Sebastian (58976784700); Warnau, Judith (60652693400); Jodlbauer, Herbert (12763825700)',
 'Gao, Jing (57212121923); Gong, Jian (55040853200); Schwarz, Nina (23986260300); Sliuzas, Richard (23006851900)',
 'Aylak, Batin Latif (56313342700)',
 'Pop-Cohuţ, Ioana-Crina (57226612127)',
 'de Alencar, Tatiana Silva (56237113500); Zaina, Luciana (6506081735)',
 'Niu, Xuezhi (59193807300); Barajas, Natalia Calvo (60652717000); Broo, Didem Gürdür (55648593700)',
 'Ismail, Sadia (57195977685); Alharbi, Abeer A.K. (59076056000); Zahra, Syeda Rabail (57190346426); Khattak, Amin Khan (60805221000); Mazhar, Tehseen (57219034600); Saudagar, Abdul Khader Jilani (56166431300); Hamam, Habib (7004762599); Khan, Muhammad Amir (56132357300)',
 'Wang, Yunan (59369798800); Yang, Huicong (60201934200); Leng, Jiaxu (60200949800); Liu, Kairui (60201764100)',
 'Zhang, Zhihan (58285529100)',
 'Pu, Yu (60620078700); Yang, Jianhui (60619863500)',
 'Aljijakli, Marwan (59791986700); Akkari, Nadine (23007535500)',
 'Nasiri, Amir Reza (58928078000); Kerachian, Reza (55975065200); Shahangian, Seyyed Ahmadreza (57223132911); Kamali, Fardin (57878592900); Najafi Dehjalali, Amirhossein (60242868000)',
 'Sakthivel, Thilagavathy (60224090500); Murugesan, Rajasekar (57188815838); Gopalan, Anitha (57924408700)',
 'Kundu, Shakti (54420380700); Ninoria, Shalini Zanzote (57216588097); Chaturvedi, Ravi Prakash (57208126664); Mishra, Annu (57267170400); Agrawal, Akshat (57213441821); Batra, Reenu (57422585400); Dubale, Mitiku (57684170000); Hashmi, Arshad (57222735849)',
 'Ying, Megan Y. (60230006500); Grandi, Daniele (57192710469); Groom, Allin (59148313300); McComb, Christopher (56400780700)',
 'Zouein, Pierrette (6602355613); Amine, Amir (60079019600); Amine, Raghad (60092818100); Jammoul, Ali (60093052000); Nashi, Mounir (60093406600); Jifetjian, Vanessa (60093406700); Smayra, Marilyn (60093052100)',
 'Friedmann, Danny (60787013900)',
 'Zykov, Sergey V. (36146486900)',
 'Bistaffa, Filippo (55516740200); Oliveira, Sergio Calo (58085284800)',
 'Naug, Avisek (57188968713); Guillen, Antonio (58248731700); Kumar, Vineet (57224775941); Greenwood, Scott (60233160100); Brewer, Wesley (57207843034); Ghorbanpour, Sahand (25641507600); Babu, Ashwin Ramesh (57192372079); Gundecha, Vineet (57219621443); Gutierrez, Ricardo Luna (57211751618); Sarkar, Soumyendu (57899989600)',
 'Trasculescu, Andrei-Costin (57220990764); Resceanu, Ionut-Cristian (16031983600); Padeanu, Ionut-Ovidiu (59960782000); Cismaru, Stefan-Irinel (57203967944); Petcu, Florina-Luminita (59961568500); Roibu, Horatiu (57202402592); Dita, Florin-Alexandru (59466666900); Iftimiciuc, Ionut-Nicusor (59960998500); Bizdoaca, Nicu-George (6506215184)',
 'Sumalatha, A. (58976489600); Sabri, Mohammad Omar (57197842391); Kumar, J. Sunil (60383479800); Vijayanandh, T. (56623137900); Lalitha, J. (60546713600); Shanmugam, N. (60547359600)',
 'Hoang, Thong (57210914382); Klymenko, Mykhailo (14056245800); Xu, Xiwei (55706225900); Pan, Shidong (57477785900); Ding, Yi (60539352800); Tang, Xushuo (58262412500); Yang, Zhengyi (57209984247); Shi, Jieke (57225119268); Lo, David (35269388000)',
 'Guo, Yujie (60099075100)',
 'Liang, Chao (59773702000); Xv, Hanyi (60629804300); Wang, Hong (60628891600); Xi, Bingyang (59773475300); Mao, Mengling (60628666200); Liu, Siyu (60629804400)',
 'Zohaib, Muhammad (57193709759); Akbar, Muhammad Azeem (57200183503); Hyrynsalmi, Sami (50361307000)',
 'Wu, Yuzhou (59938785200); Wu, Mingyang (59939197400); Deng, Peng (57190759273); Liu, Di (58678353000); Li, Kang (57445059900); Zhao, Yong (59550864400); Yin, Rong (57219200711)',
 'Jiang, Yuan-Hao (58399698000); Chen, Zi-Wei (58694658700); Zhao, Cong (59561098700); Tang, Kezong (35759841700); Duan, Jicong (58565855300); Zhou, Yizhou (59213890100)',
 'Nandhlal, Kavisha (60687020100); Kabanda, Gabriel (25723410900)',
 'Chen, Ruoxi (60413325900); Wang, Peipei (57216413976); Zheng, Xinqi (16064941200); Rao, Xinrui (60413205500); Zhang, Xiaoyuan (57729180000); Wang, Wenqi (60413027200)',
 'Cheng, Mingjun (57354963900); Jin, Hong (60199776600); Zhao, Qinfeng (57459988700); Wang, Yurun (60199304900); Wu, Yanxi (60200408100); Huang, Shan (56140282200); Yue, Wenze (8721631200)',
 'Hu, Kun (60240090200); Yao, Xifan (24385945500); Qiao, Fei (7005620707); Shen, Weiming (60423877700); Wu, Hongxing (7405584772); Yang, Wenyu (60423263700)',
 'He, Tingting (59374734700); Goh, Hui Hwang (24075809200); Pang, Wai Leong (8701196600); Phang, Swee King (36519608700); Wen, Lingyu (60413147700); Zhong, Xiaowen (60413147800)',
 'Kumar, P. Santhosh (57199976562); Pankajam, A. (57729480300); Veeraiah, Vivek (55151379400); Gharat, Adveta (57912515400); Mamatha, G. (35146519000); Roy, Devika Rani (58136306700); Gupta, Ankur (57215604870); Rajitha, N. (57773275400)',
 'Postorino, Maria Nadia (6701783667); Sarné, Giuseppe M.L. (6505830755)',
 'Dallavalle, Silvia (57849642500); Ribeiro, Luiz Ricardo Brito (59322197700); Moreira, Sérgio Adriany Santos (59228962500)',
 'Samoylova, Nadezhda A. (57202819286); Moskalenko, Igor V. (58707637000)',
 'Deng, Changhe (60017992500); Fang, Xi (37013171200)',
 'Pataranutaporn, Pat (56983058400); Doudkin, Alexander (59707675900); Maes, Pattie (56268463300)',
 'Al Hasan, Maram (59701405800); Kashef, Ayat (60777299200); Mohsen, Wissal (59758575600); Khan, Asma Gul Yousaf (60777902000); Alomari, Maryam (60777299300); Aishan, Hafsa (60126742300)',
 'Aguiar, Vinícius Alboneti (60614914200); Amorim, Leonardo Afonso (57210090261); Novais, Artur Matos Andrade (60614527100); De Jesus, Thiago Pedroso (60614431300); Da Silva Soares, Anderson (23391741100); De Oliveira, Sávio Salvarino Teles (56459632300)',
 'Coronado, Enrique (57188864138)',
 'Kim, Jiin (59193998100); Shin, Byeongjun (59979785200); Chung, Jinha (57699403200); Rhu, Minsoo (55813564600)',
 'Zhang, Jing (58236246600); Chen, Zhe (57207957994); Xiao, Ziwei (58759154600); Xu, Kan (57478338900); Ma, Tianyou (58235792400); Xiao, Fu (60235891300); Tse, Lok Him (60097621700); Cheung, Man Chit (60722293400); Lau, Ka Tai (59263197000)',
 'Arvindkumar, S. (59523705700); Ragunanthan (60238921700); Pitchaimani, Kalpana (57224479487)',
 'Akhadkar, Lavesh (60731095800); Thakre, Kalpana (37102832900); Kulkarni, Aditya (60731611900); Kadam, Parth (60731612000); Damle, Varun (60730888800)',
 'Shqair, Maram (56382413200); Sweis, Karam (59912323200); Dawkassab, Haya (59911683300); Altarazi, Safwan (24342677300); Mykoniatis, Konstantinos (55835108800)',
 'Wang, Reen-Cheng (7405335651); Hsieh, Ming-Che (55436431000); Lai, Liang-Chun (60351394300)',
 'Alvarez Castro, David (57226610120); Ford, Alistair (56246892400); Palacin, Roberto (16176000900); James, Philip (7402640970); Ziemke, Dominik (57189469071)',
 'Yls, Julius (60328311300); Yeoh, Kok Cheow (36456485100)',
 'Tao, Ming (27467918600); Su, Lingfeng (59696962700); Xie, Renping (56039766800); Dai, Hong-Ning (55602606800); Zhou, Xiaokang (55514932700)',
 'Zhang, Xugang (36722985700); Liu, Chuang (60026776800); Yue, Yong (60026502300); Gong, Qingshan (51664924200); Ma, Feng (57191358954); Wang, Yan (56274770600)',
 'Liu, Zebin (57737865900); Zhang, Xiaoheng (57221677226); Lv, Hui (60232405200); Shen, Lei (60232280200)',
 'Zhang, Yinuo (60819495500); Jia, Xing (60818701900); Wang, Zihui (60818702000); Zhou, Zhiyi (60819297600); Liu, Boyu (60819097800)',
 'Basingab, Mohammed Salem (57197831724)',
 'Rabbi, Mohammad Fazle (57219488464)',
 'Luo, Jinliang (58701805600)',
 'Liang, Zongbao (8970392500); Wang, Shichao (57202036272); Cui, Hongmei (57201072985); Feng, Junli (60241824300)',
 'Caprioli, Caterina (57209981157)',
 'Patnaik, Deepti (57222665793); Kadao, Anjali Krushna (59760802600)',
 'Lin, Fangkun (60250017000); Luo, Zhipeng (58905504100); Ma, Binyu (60646881300); Zhang, Zhiyu (60009408900); Liu, Kaiyan (60646629200); Yu, Xin (58732480000); Xu, Boyan (57211539035); Zeng, Huabin (57189357749)',
 'Bai, Yunhao (58616462200); Geng, Bing (57211018139); Yan, Hexiang (56495970700); Tao, Tao (57225802582); Hao, Jingkai (60284111800); Xin, Kunlun (16023519100)',
 'Himri, Khadija (60340267900); Joiron, Céline (6508364733); Kodad, Mohcine (57163906700)',
 'Raghupathi, Wullianallur (6603002503); Raghupathi, Viju (26032307400)',
 'Adar, Ömer (59407751400); Cihan, Onur (35776006100)',
 'Latha, Challa Madhavi (57205080757); Alvarado-Mentado, Matias (57201901936)',
 'Xin, Jie (57373621500); Zhang, Hangqi (60497458400)',
 'Sanogo, Kader (57765902700); Masmoudi, Malek (54382267200); Mekhalef Benhafssa, Abdelkader (57118277000); Sahnoun, M’hammed (37662006000)',
 'Wang, Shuping (57211559954); Li, Changhao (57820526900); Cheng, Yifeng (59635595400); Zhou, Xinyue (60256849900); Zhang, Weixin (58990983900); Cao, Yuancheng (56979443300); Cheng, Qi (57040433100)',
 'Li, Yue (57314343500); Hu, Min (58137072100); Chen, Zhijun (57195804911); Han, Yufei (60405086200); Ren, Dongyang (56706869000); Xu, Xu (55844396600); Xiong, Yunwu (14040898300); Huang, Quanzhong (57204320881); Huang, Guanhua (57040238000)',
 'Rajman, Ridhima (60149200400); Kaur, Kushalpreet (60096929500); Bhuyan, Ajatray Swagat (58194084500)',
 'Kozub, Vladyslav (59146874800); Bataiev, Sergii (59244852500); Shybko, Oksana (57203000408); Sikora, Yaroslava (57224617763); Voloshchuk, Serhii (59547490900)',
 'Bakhtadze, Natalia (6603467848); Dozortsev, Victor (6603105788); Vlasov, Artem (60354581600); Koroleva, Mariya (60353866100); Anikin, Maxim (60354581700)',
 'López-Goyez, Juan P. (59426908800); Mina, Jorge (60428420000); Arcos, Georgina (57218311944); Miranda, Jorge (60428815200)',
 'Xiao, Zixuan (59949246700); Ma, Jun (56703806400); Zhang, Siwei (58314834000)',
 'Shah, Aneri (59715772200); Modi, Krish (60159606600); Soni, Ansh (60159549000); Doshi, Nishant (37050599100)',
 'Liu, Jia’an (60160146500); Chu, Chu (59551914900); Zhao, Yilin (58306860800); Aoki, Goshi (58072734200); Xiao, Zhiqing (57670029100)',
 'Abdulameer, Susan Sabah (57209466700); Ibrahim, Yousif Munadhil (57209332374)',
 'Zarreh, Mobin (58583793300); Grogan, Paul T. (36620196300)',
 'Su, Dandan (57226809140); Neusypin, K.A. (6602995907); Dong, Ge (57192645414)',
 'Beena, B.M. (56538442100); Manideep, Thotapalli Sri Surya (57200213624); Saragadam, Sneha (59491597100); Rathi, Sailesh (60571210700); Ramesh, Ramaswamy (7201897779); Holimath, Vijay (18934957100)',
 'Ambrosino, Erica (60810115500); Andreotti, Amedeo (35564985300); Aruta, Marco (59409918300); Ballot, Gabriel (57798435300); Capone, Andrea (60498680500); de Notaristefani di Vastogirardi, Giulio (57170930000); Ferrigno, Sara (60810990600); Improta, Francesco (60215933000); Listone, Ciro (59966062700); Malvone, Vadim (57009152700); Maubert, Bastien (35092930800); Nappi, Floriana (60810698500); Romano, Salvatore (59967608600); Murano, Aniello (14061017200)',
 'Liu, Junbei (57424299600); Zhuge, Chengxiang (54953547900); Tang, Justin Hayse Chiwing G. (57424446600); Meng, Meng (60042285000); Zhang, Jie (60041650000)',
 'Du, Jinhao (58777360900); Chen, Yarong (36093728000); Mumtaz, Jabir (57204833663); Alkaabneh, Faisal (55317855100); Ji, Ziyang (59712966700); Minhas, Kaynat Afzal (58891068800)',
 'Tabassum, Shaira (57215310225); Kiss, Gabriel Hanssen (34978601700); Verma, Sachin (57203340729); Raja, Kiran (57188866050); Lindseth, Frank (6602262992)',
 'Syauqi, Ahmad (57608664200); Ramdani, Akmal (60705493300); Lim, Hankwon (14019936500); Andika, Riezqa (56197952200)',
 'Majumdar, Swarnamouli (57782341500); Awasthi, Anjali (57203055159)',
 'Abuselidze, George (57204928171); Amanova, Gulnara (56529694000); Ryskeldiyeva, Aidana (60713748300); Saduakassova, Kunsulu (57191911797)',
 'Nanoff, Tyler James (58551808100); Gonzalez Villasanti, Hugo (57192301586)',
 "Mas'udah (57204723857); Livotov, Pavel (57164768200); Kokoschko, Björn R. (57223631192); Xu, Wanyu (57355001200); Hendra, Immanuel (58499263400); Hartmann, Niklas (36606153400)",
 'Chari, Shreya K. (59705878100); Vardakas, John S. (8710803300); Ramantas, Kostas (16204223400); Verikoukis, Christos (16176716900)',
 'Calderón, Christian (59682237000); Martí, Pasqual (57218267377); Jordán, Jaume (55421766500); Palanca, Javier (23392934000); Julian, Vicente (6602206677)',
 'Pritul, Toufiq Imroze (60728544500); Ratul, Qudrat E Alahy (57468684500)',
 'Abdelnaby, Khalil M. (57209913140); Al-Husainy, Mohammed A. F. (14832362400); Alhawarat, Mohammad O. (57148556900); Rohaim, Mohamed A. (60583551800); Assar, Khairy M. (60582456000)',
 'Pareek, Sweta (60752654900); Kalaneya, Chetany (60577042900); Kumawat, Rohit (60577971400); Pareek, Shilpa (57193061543); Sharma, Yashaskar (60752655000)',
 'Fonseca i Casas, Pau (55533533700); Pi i Palomes, Xavier (57226315126)',
 'Yordanova, Zornitsa (57200724991); Nozari, Hamed (57210320748)',
 'Fagbohun, Oluwole (58932574800); Yashwanth, Sai (59733177500); Akintola, Akinyemi Sadeeq (59728892400); Wurola, Ifeoluwa (59733355200); Shittu, Lanre (59733177600); Inyang, Aniema (59733590900); Odubola, Oluwatimilehin (59676651100); Offia, Udodirim (59733774800); Olanrewaju, Said (59732638100); Toluwaleke, Ogidan (59732821100); Abutu, Ilemona (59732638200); Akinbolaji, Taiwo (59733902800)',
 'Xie, Weihong (60681798000); Yu, Juan (59524626700); Chen, Rongkang (59346430700); Li, Zhongshun (58151055800); Zheng, Diwen (57884657800)',
 'Majewska, Justyna (56519892800); Niezgoda, Agnieszka (6602508662); Truskolaski, Szymon (55849635900)',
 'Mishra, Tathastu (60765680900); Sinha, Sapna (57195607530)',
 'Kęsy, Marcin (57225051099); Britchenko, Igor (56891643900)',
 'Torgbi Agbemabiese, William (60370243900)',
 'Som, Shreya (59954368200); Patil, Samruddhi (60765116900); Pervin, Nargis (36918997800)',
 'Joshi, Varun (60166038700); Kothari, Nikita (60166893300); Kumar, Lav (60166985100)',
 'Creti, Veronica (60614920800); Rucco, Chiara (57773449100); Stefano, Alessandro (60615011500); Zampino, Francesca (58111773800); Saad, Motaz (56494148300); Longo, Antonella (57209449951); Ardebili, Ali Aghazadeh (57216462967)',
 'Parker, Laci (59710234200); Allison, Mark (55265013200)',
 'Nguyen, Bichlien H (60696903900)',
 'Anh, Tran Thi Quynh (59955961200); Nguyen-Huu, Tri (14632281000); Nguyen-Ngoc, Doanh (37018666500)',
 'Osika, Zuzanna (58569005900); Rădulescu, Roxana (57190129123); Zatarain-Salazar, Jazmin (58036549100); Oliehoek, Frans A. (15043050300); Murukannaiah, Pradeep K. (26032199400)',
 'Mariaraj, R. Jeffrey (60422780200); Lobo, Ronan (60422067900); Gowda, Maurya P (60422206700)',
 'Jaswal, Navneet (60606773200); Yadav, Bharat (60611594300); Kadian, Gagan (60611218500); Khanna, Chirag (60611687000)',
 'Gavai, Anand K. (35366319900); Meuwissen, Miranda P.M. (7003942968)',
 'Lee, Young-Chan (26662005200); Yang, Chuyu (60787965000)',
 'Krupp, Lars (57210566952); Geißler, Daniel (58183401300); Banwari, Vishal (59956340100); Lukowicz, Paul (6701557151); Karolus, Jakob (56644671700)',

In [41]:
 df

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,NaN,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,NaN,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,979-833159409-1,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,Andrew K.; Zia A.; Rizzo D.,"Andrew, Kevin (59264606600); Zia, Asim (572234...",59264606600; 57223446194; 7005922424,Integrating Deep Reinforcement Learning into A...,2024,Lecture Notes in Networks and Systems,1066 LNNS,NaN,NaN,221,...,978-303166427-4,NaN,NaN,English,Lect. Notes Networks Syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85201106911
871,Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.,"Tew, Yishen (58700122400); Fu, Ling (577214082...",58700122400; 57721408200; 59081900100; 5772168...,Construction of Knowledge Graph for Material a...,2024,Energy Proceedings,44,NaN,NaN,NaN,...,NaN,NaN,NaN,English,Energy. Proc.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85190366728
872,Ullah K.M.; Oladosu G.A.; Crooks A.,"Ullah, Kazi Masel (56239217200); Oladosu, Gbad...",56239217200; 6602587328; 25521036800,Evaluating the incentive for soil organic carb...,2023,Journal of Environmental Management,348,NaN,119418,NaN,...,NaN,JEVMA,37871549.0,English,J. Environ. Manage.,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-85174450993
873,Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...,"Shen, Weiwei (57346991900); Marín Del Valle, T...",57346991900; 57226063061; 57196091876; 5719626...,Scenario analyses of mariculture expansion in ...,2024,"Resources, Conservation and Recycling",204,NaN,107508,NaN,...,NaN,RCREE,NaN,English,Resour. Conserv. Recycl.,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85186448959
874,Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....,"Kaiser, Jan (57383738200); Hernández, Marco Pé...",57383738200; 57209478009; 57563066400; 5721506...,An agent-based approach for energy-efficient s...,2024,Engineering Applications of Artificial Intelli...,127,NaN,107198,NaN,...,NaN,EAAIE,NaN,English,Eng Appl Artif Intell,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85172726735

In [42]:
df["new_column"] = "Md Naquiuzzaman"
df

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID,new_column
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328,Md Naquiuzzaman
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038,Md Naquiuzzaman
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114,Md Naquiuzzaman
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358,Md Naquiuzzaman
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589,Md Naquiuzzaman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,Andrew K.; Zia A.; Rizzo D.,"Andrew, Kevin (59264606600); Zia, Asim (572234...",59264606600; 57223446194; 7005922424,Integrating Deep Reinforcement Learning into A...,2024,Lecture Notes in Networks and Systems,1066 LNNS,NaN,NaN,221,...,NaN,NaN,English,Lect. Notes Networks Syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85201106911,Md Naquiuzzaman
871,Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.,"Tew, Yishen (58700122400); Fu, Ling (577214082...",58700122400; 57721408200; 59081900100; 5772168...,Construction of Knowledge Graph for Material a...,2024,Energy Proceedings,44,NaN,NaN,NaN,...,NaN,NaN,English,Energy. Proc.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85190366728,Md Naquiuzzaman
872,Ullah K.M.; Oladosu G.A.; Crooks A.,"Ullah, Kazi Masel (56239217200); Oladosu, Gbad...",56239217200; 6602587328; 25521036800,Evaluating the incentive for soil organic carb...,2023,Journal of Environmental Management,348,NaN,119418,NaN,...,JEVMA,37871549.0,English,J. Environ. Manage.,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-85174450993,Md Naquiuzzaman
873,Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...,"Shen, Weiwei (57346991900); Marín Del Valle, T...",57346991900; 57226063061; 57196091876; 5719626...,Scenario analyses of mariculture expansion in ...,2024,"Resources, Conservation and Recycling",204,NaN,107508,NaN,...,RCREE,NaN,English,Resour. Conserv. Recycl.,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85186448959,Md Naquiuzzaman
874,Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....,"Kaiser, Jan (57383738200); Hernández, Marco Pé...",57383738200; 57209478009; 57563066400; 5721506...,An agent-based approach for energy-efficient s...,2024,Engineering Applications of Artificial Intelli...,127,NaN,107198,NaN,...,EAAIE,NaN,English,Eng Appl Artif Intell,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85172726735,Md Naquiuzzaman

In [43]:
df["new_column"] = list(range(len(df)))

In [44]:
df

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID,new_column
0,Tou Y.; Nagamatsu A.; Watanabe C.,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103...",6603292302; 7103054512; 55619319799,The New Perspective on Sustainability—Lessons ...,2026,Sustainability (Switzerland),18,5,2402,NaN,...,NaN,NaN,English,Sustainability,Article,Final,All Open Access; Gold Open Access; Green Open ...,Scopus,2-s2.0-105032683328,0
1,Guzmán E.; Andrés B.; Torres-Polo M.,"Guzmán, Eduardo (57217008411); Andrés, Beatriz...",57217008411; 55508042400; 57890088200,A cooperative digital twin–multi-agent reinfor...,2026,Computers and Industrial Engineering,218,NaN,112044,NaN,...,CINDD,NaN,English,Comput Ind Eng,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-105039095038,1
2,Yuan M.; Guo X.; Hu J.; Yang Y.,"Yuan, Mingkang (57219867444); Guo, Xueling (60...",57219867444; 60609808300; 60077617800; 5815708...,Multi-agent reinforcement learning for competi...,2026,Journal of Hydrology,677,NaN,135782,NaN,...,JHYDA,NaN,English,J. Hydrol.,Article,Final,NaN,Scopus,2-s2.0-105040726114,2
3,Alzu'Bi S.; Mughaid A.,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57...",60535988400; 57209223613,The Digital Farmer Agents in Precise and Susta...,2025,2025 3rd International Conference on Foundatio...,NaN,NaN,NaN,202,...,NaN,NaN,English,"Int. Conf. Found. Large Lang. Model, FLLM",Conference paper,Final,NaN,Scopus,2-s2.0-105035879358,3
4,Chootongchai S.; Maneerat P.,"Chootongchai, Suparoek (56857620000); Maneerat...",56857620000; 57191034244,NextGen Talent-Driven AI Educational Agent,2026,International Journal of Information and Educa...,16,3,NaN,658,...,NaN,NaN,English,Int. J. Inf. Educ. Technol.,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105032992589,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,Andrew K.; Zia A.; Rizzo D.,"Andrew, Kevin (59264606600); Zia, Asim (572234...",59264606600; 57223446194; 7005922424,Integrating Deep Reinforcement Learning into A...,2024,Lecture Notes in Networks and Systems,1066 LNNS,NaN,NaN,221,...,NaN,NaN,English,Lect. Notes Networks Syst.,Conference paper,Final,NaN,Scopus,2-s2.0-85201106911,870
871,Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.,"Tew, Yishen (58700122400); Fu, Ling (577214082...",58700122400; 57721408200; 59081900100; 5772168...,Construction of Knowledge Graph for Material a...,2024,Energy Proceedings,44,NaN,NaN,NaN,...,NaN,NaN,English,Energy. Proc.,Conference paper,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85190366728,871
872,Ullah K.M.; Oladosu G.A.; Crooks A.,"Ullah, Kazi Masel (56239217200); Oladosu, Gbad...",56239217200; 6602587328; 25521036800,Evaluating the incentive for soil organic carb...,2023,Journal of Environmental Management,348,NaN,119418,NaN,...,JEVMA,37871549.0,English,J. Environ. Manage.,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-85174450993,872
873,Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...,"Shen, Weiwei (57346991900); Marín Del Valle, T...",57346991900; 57226063061; 57196091876; 5719626...,Scenario analyses of mariculture expansion in ...,2024,"Resources, Conservation and Recycling",204,NaN,107508,NaN,...,RCREE,NaN,English,Resour. Conserv. Recycl.,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85186448959,873
874,Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....,"Kaiser, Jan (57383738200); Hernández, Marco Pé...",57383738200; 57209478009; 57563066400; 5721506...,An agent-based approach for energy-efficient s...,2024,Engineering Applications of Artificial Intelli...,127,NaN,107198,NaN,...,EAAIE,NaN,English,Eng Appl Artif Intell,Article,Final,All Open Access; Green Open Access; Hybrid Gol...,Scopus,2-s2.0-85172726735,874

In [45]:
list(range(len(df)))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874]

In [46]:
df.columns

Index(['Authors', 'Author full names', 'Author(s) ID', 'Title', 'Year',
       'Source title', 'Volume', 'Issue', 'Art. No.', 'Page start', 'Page end',
       'Cited by', 'DOI', 'Link', 'Affiliations', 'Authors with affiliations',
       'Abstract', 'Author Keywords', 'Index Keywords',
       'Molecular Sequence Numbers', 'Chemicals/CAS', 'Tradenames',
       'Manufacturers', 'Funding Details', 'Funding Texts', 'References',
       'Correspondence Address', 'Editors', 'Publisher', 'Sponsors',
       'Conference name', 'Conference date', 'Conference location',
       'Conference code', 'ISSN', 'ISBN', 'CODEN', 'PubMed ID',
       'Language of Original Document', 'Abbreviated Source Title',
       'Document Type', 'Publication Stage', 'Open Access', 'Source', 'EID',
       'new_column'],
      dtype='str')

In [47]:
df[['Authors', 'Author(s) ID' , 'Author full names']]

,Authors,Author(s) ID,Author full names
0,Tou Y.; Nagamatsu A.; Watanabe C.,6603292302; 7103054512; 55619319799,"Tou, Yuji (6603292302); Nagamatsu, Akira (7103..."
1,Guzmán E.; Andrés B.; Torres-Polo M.,57217008411; 55508042400; 57890088200,"Guzmán, Eduardo (57217008411); Andrés, Beatriz..."
2,Yuan M.; Guo X.; Hu J.; Yang Y.,57219867444; 60609808300; 60077617800; 5815708...,"Yuan, Mingkang (57219867444); Guo, Xueling (60..."
3,Alzu'Bi S.; Mughaid A.,60535988400; 57209223613,"Alzu'Bi, Shadi (60535988400); Mughaid, Ala (57..."
4,Chootongchai S.; Maneerat P.,56857620000; 57191034244,"Chootongchai, Suparoek (56857620000); Maneerat..."
...,...,...,...
870,Andrew K.; Zia A.; Rizzo D.,59264606600; 57223446194; 7005922424,"Andrew, Kevin (59264606600); Zia, Asim (572234..."
871,Tew Y.; Fu L.; Li J.; Sun T.; Li L.; Wang X.,58700122400; 57721408200; 59081900100; 5772168...,"Tew, Yishen (58700122400); Fu, Ling (577214082..."
872,Ullah K.M.; Oladosu G.A.; Crooks A.,56239217200; 6602587328; 25521036800,"Ullah, Kazi Masel (56239217200); Oladosu, Gbad..."
873,Shen W.; Marín Del Valle T.; Wu J.; Chen Y.; W...,57346991900; 57226063061; 57196091876; 5719626...,"Shen, Weiwei (57346991900); Marín Del Valle, T..."
874,Kaiser J.; Hernández M.P.; Kaupe V.; Kurrek P....,57383738200; 57209478009; 57563066400; 5721506...,"Kaiser, Jan (57383738200); Hernández, Marco Pé..."

In [48]:
import pandas as pd

# Read the CSV file
df = pd.read_csv(r"D:\churnguard_targeted_retention_list.csv")

# Convert CSV to Excel
df.to_excel(r"D:\churnguard_targeted_retention_list.xlsx", index=False)

print("File converted successfully!")

File converted successfully!

In [49]:
import pandas as pd

df1 = pd.read_excel(r"D:\churnguard_targeted_retention_list.xlsx")

df1

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
0,CUST-13880,Male,No,No,No,1,Yes,Yes,Fiber optic,No,...,Electronic check,111.63,113.95,346.2,2,3,1,1,0.9869,High Risk
1,CUST-11066,Male,Yes,No,No,9,Yes,No,DSL,No,...,Electronic check,84.64,784.75,108.2,4,7,2,1,0.9818,High Risk
2,CUST-10599,Male,Yes,No,Yes,2,No,No phone service,Fiber optic,No,...,Electronic check,74.94,149.87,283.6,3,1,1,1,0.9772,High Risk
3,CUST-10192,Female,No,Yes,Yes,4,No,No phone service,Fiber optic,No,...,Electronic check,84.15,323.44,170.9,1,3,2,1,0.9739,High Risk
4,CUST-13852,Female,No,No,No,4,Yes,No,Fiber optic,No,...,Bank transfer (automatic),91.35,362.79,269.2,1,4,1,1,0.9729,High Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,CUST-14232,Male,No,No,No,63,Yes,Yes,No,No internet service,...,Mailed check,44.35,2881.47,5.5,1,1,5,0,0.0099,Low Risk
1296,CUST-10162,Female,No,No,Yes,72,Yes,Yes,DSL,No,...,Electronic check,106.51,7954.47,143.6,0,1,5,0,0.0080,Low Risk
1297,CUST-14311,Female,No,No,No,70,No,No phone service,DSL,No,...,Credit card (automatic),52.71,3509.48,102.2,0,1,5,0,0.0070,Low Risk
1298,CUST-13862,Male,Yes,Yes,Yes,67,No,No phone service,DSL,No,...,Mailed check,72.66,4904.29,159.3,0,1,5,0,0.0060,Low Risk
1299,CUST-13053,Male,No,No,No,70,No,No phone service,DSL,No,...,Mailed check,62.85,4336.33,104.4,0,0,5,0,0.0049,Low Risk

In [50]:
df1.shape

(1300, 27)

In [51]:
df1.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure_months', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract_type',
       'paperless_billing', 'payment_method', 'monthly_charges',
       'total_charges', 'avg_monthly_usage_gb', 'payment_delay_days',
       'support_tickets_count', 'customer_satisfaction_score', 'churn',
       'churn_probability', 'risk_tier'],
      dtype='str')

In [52]:
df1.dtypes

customer_id                        str
gender                             str
senior_citizen                     str
partner                            str
dependents                         str
tenure_months                    int64
phone_service                      str
multiple_lines                     str
internet_service                   str
online_security                    str
online_backup                      str
device_protection                  str
tech_support                       str
streaming_tv                       str
streaming_movies                   str
contract_type                      str
paperless_billing                  str
payment_method                     str
monthly_charges                float64
total_charges                  float64
avg_monthly_usage_gb           float64
payment_delay_days               int64
support_tickets_count            int64
customer_satisfaction_score      int64
churn                            int64
churn_probability              float64
risk_tier                          str
dtype: object

In [53]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  1300 non-null   str
 1   gender                       1300 non-null   str
 2   senior_citizen               1300 non-null   str
 3   partner                      1300 non-null   str
 4   dependents                   1300 non-null   str
 5   tenure_months                1300 non-null   int64
 6   phone_service                1300 non-null   str
 7   multiple_lines               1300 non-null   str
 8   internet_service             1300 non-null   str
 9   online_security              1300 non-null   str
 10  online_backup                1300 non-null   str
 11  device_protection            1300 non-null   str
 12  tech_support                 1300 non-null   str
 13  streaming_tv                 1300 non-null   str
 14  streaming_movies             1300 non-null   str
 15  contract_type                1300 non-null   str
 16  paperless_billing            1300 non-null   str
 17  payment_method               1300 non-null   str
 18  monthly_charges              1300 non-null   float64
 19  total_charges                1300 non-null   float64
 20  avg_monthly_usage_gb         1300 non-null   float64
 21  payment_delay_days           1300 non-null   int64
 22  support_tickets_count        1300 non-null   int64
 23  customer_satisfaction_score  1300 non-null   int64
 24  churn                        1300 non-null   int64
 25  churn_probability            1300 non-null   float64
 26  risk_tier                    1300 non-null   str
dtypes: float64(4), int64(5), str(18)
memory usage: 413.8 KB

In [54]:
df1.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
0,CUST-13880,Male,No,No,No,1,Yes,Yes,Fiber optic,No,...,Electronic check,111.63,113.95,346.2,2,3,1,1,0.9869,High Risk
1,CUST-11066,Male,Yes,No,No,9,Yes,No,DSL,No,...,Electronic check,84.64,784.75,108.2,4,7,2,1,0.9818,High Risk
2,CUST-10599,Male,Yes,No,Yes,2,No,No phone service,Fiber optic,No,...,Electronic check,74.94,149.87,283.6,3,1,1,1,0.9772,High Risk
3,CUST-10192,Female,No,Yes,Yes,4,No,No phone service,Fiber optic,No,...,Electronic check,84.15,323.44,170.9,1,3,2,1,0.9739,High Risk
4,CUST-13852,Female,No,No,No,4,Yes,No,Fiber optic,No,...,Bank transfer (automatic),91.35,362.79,269.2,1,4,1,1,0.9729,High Risk

In [55]:
df1.tail()

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
1295,CUST-14232,Male,No,No,No,63,Yes,Yes,No,No internet service,...,Mailed check,44.35,2881.47,5.5,1,1,5,0,0.0099,Low Risk
1296,CUST-10162,Female,No,No,Yes,72,Yes,Yes,DSL,No,...,Electronic check,106.51,7954.47,143.6,0,1,5,0,0.0080,Low Risk
1297,CUST-14311,Female,No,No,No,70,No,No phone service,DSL,No,...,Credit card (automatic),52.71,3509.48,102.2,0,1,5,0,0.0070,Low Risk
1298,CUST-13862,Male,Yes,Yes,Yes,67,No,No phone service,DSL,No,...,Mailed check,72.66,4904.29,159.3,0,1,5,0,0.0060,Low Risk
1299,CUST-13053,Male,No,No,No,70,No,No phone service,DSL,No,...,Mailed check,62.85,4336.33,104.4,0,0,5,0,0.0049,Low Risk

In [56]:
df1.head(2)

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
0,CUST-13880,Male,No,No,No,1,Yes,Yes,Fiber optic,No,...,Electronic check,111.63,113.95,346.2,2,3,1,1,0.9869,High Risk
1,CUST-11066,Male,Yes,No,No,9,Yes,No,DSL,No,...,Electronic check,84.64,784.75,108.2,4,7,2,1,0.9818,High Risk

In [57]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  1300 non-null   str
 1   gender                       1300 non-null   str
 2   senior_citizen               1300 non-null   str
 3   partner                      1300 non-null   str
 4   dependents                   1300 non-null   str
 5   tenure_months                1300 non-null   int64
 6   phone_service                1300 non-null   str
 7   multiple_lines               1300 non-null   str
 8   internet_service             1300 non-null   str
 9   online_security              1300 non-null   str
 10  online_backup                1300 non-null   str
 11  device_protection            1300 non-null   str
 12  tech_support                 1300 non-null   str
 13  streaming_tv                 1300 non-null   str
 14  streaming_movies             1300 non-null   str
 15  contract_type                1300 non-null   str
 16  paperless_billing            1300 non-null   str
 17  payment_method               1300 non-null   str
 18  monthly_charges              1300 non-null   float64
 19  total_charges                1300 non-null   float64
 20  avg_monthly_usage_gb         1300 non-null   float64
 21  payment_delay_days           1300 non-null   int64
 22  support_tickets_count        1300 non-null   int64
 23  customer_satisfaction_score  1300 non-null   int64
 24  churn                        1300 non-null   int64
 25  churn_probability            1300 non-null   float64
 26  risk_tier                    1300 non-null   str
dtypes: float64(4), int64(5), str(18)
memory usage: 413.8 KB

In [58]:
df1.sample(4)

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
1,CUST-11066,Male,Yes,No,No,9,Yes,No,DSL,No,...,Electronic check,84.64,784.75,108.2,4,7,2,1,0.9818,High Risk
965,CUST-15941,Male,No,Yes,No,44,Yes,No,No,No internet service,...,Credit card (automatic),33.45,1442.54,8.4,0,5,3,0,0.1661,Low Risk
1114,CUST-11259,Female,No,Yes,No,23,Yes,Yes,DSL,No,...,Mailed check,87.51,2064.72,122.7,1,0,3,0,0.0777,Low Risk
629,CUST-16183,Female,No,No,Yes,12,Yes,No,No,No internet service,...,Mailed check,36.55,428.01,8.5,1,1,4,0,0.4479,Medium Risk

In [59]:
df1[["partner"]]

     partner
0         No
1         No
2         No
3        Yes
4         No
...      ...
1295      No
1296      No
1297      No
1298     Yes
1299      No

[1300 rows x 1 columns]

In [60]:
bf = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
bf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [61]:
bf.describe()  # df.describe() gives statistical information about numerical column

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [62]:
bf.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [63]:
bf.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [64]:
bf.dtypes[bf.dtypes == "object"]

Series([], dtype: object)

In [65]:
bf.dtypes[bf.dtypes == "object"].index

Index([], dtype='str')

In [66]:
bf[bf.dtypes[bf.dtypes == "object"].index]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[891 rows x 0 columns]

In [67]:
bf[bf.dtypes[bf.dtypes != "object"].index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [79]:
bf[bf.dtypes[bf.dtypes == "object"].index].describe()

ValueError: Cannot describe a DataFrame without columns

In [70]:
s = bf[bf.dtypes[bf.dtypes != "object"].index].describe().reset_index()

In [71]:
s

,index,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
0,count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
1,mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
2,std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
3,min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
4,25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
5,50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
6,75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
7,max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [74]:
round (s["Pclass"],1)

0    891.0
1      2.3
2      0.8
3      1.0
4      2.0
5      3.0
6      3.0
7      3.0
Name: Pclass, dtype: float64

In [76]:
bf.describe(include = "object")

C:\Users\Naquiuzzaman\AppData\Local\Temp\ipykernel_37328\1046821905.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  bf.describe(include = "object")

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [77]:
bf.describe(include = "all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [82]:
#iloc >> integeger/implict
#loc >> explicit index

In [86]:
s.iloc[0:100]

,index,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
0,count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
1,mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
2,std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
3,min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
4,25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
5,50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
6,75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
7,max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [88]:
bf.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [89]:
df.loc[0:5]

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
0,CUST-13880,Male,No,No,No,1,Yes,Yes,Fiber optic,No,...,Electronic check,111.63,113.95,346.2,2,3,1,1,0.9869,High Risk
1,CUST-11066,Male,Yes,No,No,9,Yes,No,DSL,No,...,Electronic check,84.64,784.75,108.2,4,7,2,1,0.9818,High Risk
2,CUST-10599,Male,Yes,No,Yes,2,No,No phone service,Fiber optic,No,...,Electronic check,74.94,149.87,283.6,3,1,1,1,0.9772,High Risk
3,CUST-10192,Female,No,Yes,Yes,4,No,No phone service,Fiber optic,No,...,Electronic check,84.15,323.44,170.9,1,3,2,1,0.9739,High Risk
4,CUST-13852,Female,No,No,No,4,Yes,No,Fiber optic,No,...,Bank transfer (automatic),91.35,362.79,269.2,1,4,1,1,0.9729,High Risk
5,CUST-15004,Female,No,No,No,2,Yes,Yes,Fiber optic,No,...,Electronic check,129.91,261.17,278.4,3,2,2,1,0.9715,High Risk

In [90]:
df.loc[5:6
    ]

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
5,CUST-15004,Female,No,No,No,2,Yes,Yes,Fiber optic,No,...,Electronic check,129.91,261.17,278.4,3,2,2,1,0.9715,High Risk
6,CUST-12997,Male,No,No,No,2,Yes,Yes,Fiber optic,Yes,...,Credit card (automatic),109.39,214.54,189.2,2,2,1,1,0.9672,High Risk

In [91]:
df.iloc[5:6
    ]

,customer_id,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,online_security,...,payment_method,monthly_charges,total_charges,avg_monthly_usage_gb,payment_delay_days,support_tickets_count,customer_satisfaction_score,churn,churn_probability,risk_tier
5,CUST-15004,Female,No,No,No,2,Yes,Yes,Fiber optic,No,...,Electronic check,129.91,261.17,278.4,3,2,2,1,0.9715,High Risk

In [93]:
df.iloc[3:5, 7:9]

     multiple_lines internet_service
3  No phone service      Fiber optic
4                No      Fiber optic

In [95]:
bf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [96]:
bf["Pclass"].nunique()

3

In [97]:
bf["Name"].nunique()

891

In [98]:
bf["Sex"].nunique()

2

In [103]:
bf["Sex"].value_counts # you can visualize the male kon hai or female kon hai through the value_counts

<bound method IndexOpsMixin.value_counts of 0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str>

In [104]:
bf["Sex"].value_counts(normalize = True) # Through normalise you can see the sam,e data ij percentage

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [106]:
bf["Sex"].nunique()

2

In [107]:
bf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [119]:
bf.drop(1, inplace = True)

In [120]:
bf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [123]:
# for dropping the passenger class 
bf.drop("Pclass",axis =1,inplace = True)

In [124]:
bf

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [126]:
bf.sort_values( by = "Name")

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S
746,747,0,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.2500,NaN,S
279,280,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S
308,309,0,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.0000,NaN,C
874,875,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
286,287,1,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.5000,NaN,S
282,283,0,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5000,NaN,S
361,362,0,"del Carlo, Mr. Sebastiano",male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
153,154,0,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
868,869,0,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S

In [129]:
bf.sort_values( by = "Age")

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
831,832,1,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S